### ISSUE TITLE
Error TS2345: Argument of type 'WrappedDocument<CustomDocument>' is not assignable to parameter of type 'VerificationBuilderOptions'

### ISSUE THREAD

**Issue by wmtwebteam** [OpenCerts/verify#31]
Hi team, below line is issuing error as mentioned in the title:
`const fragments = await verify(documentMainnetValidWithCertificateStore);`

But when I provided the 2nd parameter as mentioned in the [Usage example](https://github.com/OpenCerts/verify/tree/master), as below:
`const fragments = await verify(documentMainnetValidWithCertificateStore, { network: "goerli" });`

..then again, it issues different error which says `Expected 1 arguments, but got 2.ts(2554)`.

Please kindly advise. Thanks everyone.

**Comment by zixiang2018** [comment]
Hi @wmtwebteam , you may refer to [this example for your use case](https://github.com/OpenCerts/verify/blob/2cf0d8a993ecfabf97eed0fec350077afe88e0d9/test/verify.v2.test.ts#L28)

The result should look like this (assuming you are verifying on Sepolia Testnet),
```javascript
import { verify } from "@govtechsg/opencerts-verify";
const sepoliaVerify = verify({
  network: "sepolia",
});
const fragments = await sepoliaVerify(document);

```
